name: Compiles

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2020-01-07
        components: rustfmt
        target: wasm32-unknown-unknown
        default: true 
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Compile Modules
      run: cd modules && cargo build --all
